// <auto-generated />
using System;
using HikingRoutes.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HikingRoutes.API.Migrations
{
    [DbContext(typeof(HikingRoutesDbContext))]
    [Migration("20231120125649_SeedRoutesToDb")]
    partial class SeedRoutesToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HikingRoutes.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7f416be-0f78-4b45-addd-a1a43762427f"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("9fed6056-25e4-41cc-b5c9-2a0876666ae6"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("b71a2d0d-9a0b-4304-9ba5-1eb32e4138ce"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("HikingRoutes.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50833652-7384-4be5-9443-3a69e97be660"),
                            Code = "VAR",
                            Name = "Varna",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Varna_in_Bulgaria.svg/1024px-Varna_in_Bulgaria.svg.png"
                        },
                        new
                        {
                            Id = new Guid("652a2535-537b-48bb-b086-27a71ca43e63"),
                            Code = "BUR",
                            Name = "Burgas",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Burgas_in_Bulgaria.svg/1024px-Burgas_in_Bulgaria.svg.png"
                        },
                        new
                        {
                            Id = new Guid("2297cc62-fb63-445f-8d33-ce1e6bde7253"),
                            Code = "PLO",
                            Name = "Plovdiv",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Plovdiv_in_Bulgaria.svg/250px-Plovdiv_in_Bulgaria.svg.png"
                        },
                        new
                        {
                            Id = new Guid("16f957c9-38f4-412b-9114-3c43a37be938"),
                            Code = "PLE",
                            Name = "Pleven",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Pleven_in_Bulgaria.svg/1024px-Pleven_in_Bulgaria.svg.png"
                        },
                        new
                        {
                            Id = new Guid("bea9e721-0e04-42e6-bc82-5e012855e9ec"),
                            Code = "SOF",
                            Name = "Sofia",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Sofia_%28province%29_in_Bulgaria.svg/1024px-Sofia_%28province%29_in_Bulgaria.svg.png"
                        },
                        new
                        {
                            Id = new Guid("91778c76-44f2-4ac7-8108-05bedb5372cd"),
                            Code = "SLI",
                            Name = "Sliven",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Sliven_in_Bulgaria.svg/1024px-Sliven_in_Bulgaria.svg.png"
                        },
                        new
                        {
                            Id = new Guid("f0c54f28-6e10-4598-a752-199b5401784b"),
                            Code = "SIL",
                            Name = "Silistra",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Silistra_in_Bulgaria.svg/1024px-Silistra_in_Bulgaria.svg.png"
                        },
                        new
                        {
                            Id = new Guid("66af9c30-8a1e-4c81-a287-148ebc2af9f2"),
                            Code = "YAM",
                            Name = "Yambol",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Yambol_in_Bulgaria.svg/1024px-Yambol_in_Bulgaria.svg.png"
                        },
                        new
                        {
                            Id = new Guid("0d888ba2-f037-4414-a3da-1ac0c8a36932"),
                            Code = "VID",
                            Name = "Vidin",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Yambol_in_Bulgaria.svg/1024px-Yambol_in_Bulgaria.svg.png"
                        });
                });

            modelBuilder.Entity("HikingRoutes.API.Models.Domain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("06f08587-dc1f-426f-86c2-40357d7c139b"),
                            Description = "копътеката започва над стария квартал \"Варуша\" и се изкачва по североизточните склонове на \"Картала\", като колкото по-високо се качва, толкова гледката към старата част на града става по-панорамна и красива. Оттук пътеката се спуска през местност наречена \"Зелени дол\", за да достигне до красив водопад. След водопада се продължава в подножието на западния скален венец на прохода Дервент, през който река Янтра напуска Търново и се отправя в северна посока към Дунавската равнина, за да се достигне до манастира. Това е добра възможност за разходка сред природата, комбинирана с посещение на Преображенския манастир, чрез която да се разтоварите и заредите с положителни емоции.",
                            DifficultyId = new Guid("cfdb74d0-8ef8-43ba-81a5-cc6d5fe36270"),
                            LengthInKm = 3.0,
                            Name = "Екопътека до Преображенския манастир",
                            RegionId = new Guid("f9f73085-0059-4837-85e2-6995d0656b82"),
                            WalkImageUrl = "https://www.bestplacesinbulgaria.com/wp-content/uploads/2017/01/preobrajenski-monastery-stara-planina-mountain-tourist-eco-route-04.jpg"
                        },
                        new
                        {
                            Id = new Guid("7dcd875f-e3c3-4fbb-88c2-9c1a2c1b02dc"),
                            Description = "Маршрутът е с историческа и биологична насоченост и с продължителност около 2 ч. 30 м.\r\nНачалото на Хайдушката пътека е до Информационно-Посетителския център на парка. По маркирана пътека след около 2 часа се достига до Туристически комплекс Карандила. Поема се на север по асфалтов път и след 30 минути се достига извора Кушбунар, разположен във вековна букова гора, която е обявена за природна забележителност.",
                            DifficultyId = new Guid("777c4644-a5f7-42a5-a086-44ecd5ece1ce"),
                            LengthInKm = 6.0,
                            Name = "Хайдушка пътека гр.Сливен ",
                            RegionId = new Guid("81ad011c-60f0-4969-90db-219e3e2a5728"),
                            WalkImageUrl = "https://tripsjournal.com/wp-content/uploads/2016/03/kym-ravninata.jpg"
                        },
                        new
                        {
                            Id = new Guid("b303934a-37a1-4963-ba00-ce9b4cbd960a"),
                            Description = "Този туристически маршрут води началото си от село Сирищник и води до изкачване на най-високия връх на планина Рудини – връх Сирищнишка рудина. Името на екопътека „Поглед към девет планини“, както можете да се досетите, идва от зашеметяващата гледка във всички посоки от вишката, изградена на върха. Указателна табела ще ви насочи накъде какво виждате, но лично според мен се виждат повече от 9 планини. По пътя нагоре ще минете по горска пътека, покрай един малък параклис, по виещо дървено стълбище, ще поставите и своя камък в интересната мозайка „Окото“, след което ще изкачите и връх Сирищнишка рудина. ",
                            DifficultyId = new Guid("cfdb74d0-8ef8-43ba-81a5-cc6d5fe36270"),
                            LengthInKm = 6.0,
                            Name = "Екопътека „Поглед към девет планини“ ",
                            RegionId = new Guid("6ed072ff-7d65-4288-851b-0d7669060ce9"),
                            WalkImageUrl = "https://tripsjournal.com/wp-content/uploads/2016/03/po-stylbite-nadolu-300x169.jpg"
                        },
                        new
                        {
                            Id = new Guid("b1187cee-242a-44df-908f-2f58a77d979c"),
                            Description = "До екопътеката може да стигнете лесно от Плевен в посока Ловеч, преминавайки през селата Брестовец и Тодорово и Горталово. Освен, че ще се озовете в пълен унисон с природата, в мястото са изградени много барбекюта, беседки и места за отдих.",
                            DifficultyId = new Guid("b26b0570-cf97-49a6-a74e-acf6ed6c58d0"),
                            LengthInKm = 7.0,
                            Name = "Екопътека Чернелка",
                            RegionId = new Guid("c94159c3-715c-4ed1-8649-6a28130d5563"),
                            WalkImageUrl = "https://www.360mag.bg/wp-content/uploads/2020/06/%D0%B5%D0%BA%D0%BE%D0%BF%D1%8A%D1%82%D0%B5%D0%BA%D0%B0-%D1%87%D0%B5%D1%80%D0%BD%D0%B5%D0%BB%D0%BA%D0%B0.jpg"
                        },
                        new
                        {
                            Id = new Guid("832ede53-1886-469a-a547-a82c05caee2a"),
                            Description = "Районът се отличава с красива природа и най-вече със страхотна кухня. Отправяме се на път към екопътека „Бяла река”. Ще стигнете и до бивак Бялата река, от който започва и красивата екопътека. Разкриват се уникални гледки от реката и малки водопади. Тук могат да бъдат видени 11 уникални за района растителни вида. В Национален парк Централен балкан също така има и огромно разнообразие от животински видове, сред които: мечки, вълци, диви кози, царски орли и редица други.",
                            DifficultyId = new Guid("777c4644-a5f7-42a5-a086-44ecd5ece1ce"),
                            LengthInKm = 8.0,
                            Name = "Бяла река",
                            RegionId = new Guid("da1d1365-ee7e-43f5-95f4-90b4eebaf65c"),
                            WalkImageUrl = "https://trafficnews.bg/data/images/2021_04_28/DSC_0085-800x500.jpg"
                        });
                });

            modelBuilder.Entity("HikingRoutes.API.Models.Domain.Route", b =>
                {
                    b.HasOne("HikingRoutes.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingRoutes.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
